apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-prd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/demetrio79/kind.git
    targetRevision: main
    path: apps/demo-app/prd
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app-prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
